function clean(s){return String(s||'').replace(/\s+/g,' ').trim();}
function normISBN(s){return String(s||'').replace(/[^0-9Xx]/g,'').toUpperCase();}
function escHtml(s){return String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
async function json(url, init={}){try{const r=await fetch(url,{...init,headers:{Accept:'application/json',...(init.headers||{})}});if(!r.ok)return null;return await r.json();}catch(_){return null;}}
async function html(url){try{const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html,application/xhtml+xml,*/*;q=0.8'}});if(!r.ok)return '';return await r.text();}catch(_){return '';}}
function ogImage(s){const m=s.match(/<meta[^>]+(?:property|name)=["']og:image["'][^>]+content=["']([^"']+)/i)||s.match(/<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']og:image["']/i);return m?m[1].replace(/&amp;/g,'&'):'';}
function jsonLd(s){const out=[];const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(s))){try{const x=JSON.parse(m[1]);(Array.isArray(x)?x:[x]).forEach(o=>o&&out.push(o));}catch(_){}}return out;}
function parseCataloguePage(s,url,q){const ld=jsonLd(s);const book=ld.find(x=>/Book|Product/i.test(String(x['@type']||'')))||{};const author=book.author;const authors=author?(Array.isArray(author)?author.map(x=>typeof x==='string'?x:x.name||''):[typeof author==='string'?author:author.name||'']):[];const title=book.name||((s.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)||[])[1])||'';const isbnRaw=book.isbn||((s.match(/(?:ISBN(?:-13)?|EAN)[^0-9]{0,30}(97[89][0-9 -]{10,20})/i)||[])[1]||'');const isbn=normISBN(isbnRaw);const pub=((s.match(/(?:Editora|Publisher)[^A-Za-z0-9]{0,20}([^<|\n]{2,80})/i)||[])[1]||'').trim();const year=((s.match(/(?:20|19)\d{2}/)||[])[0]||'');const image=book.image||ogImage(s);return {title:clean(title.replace(/<[^>]+>/g,' ')),authors:authors.filter(Boolean),publisher:clean(pub),publishedDate:year,language:'pt-BR',isbn:isbn||(/^97[89]\d{10}$/.test(q)?q:''),cover:image,url,source:'Brazil catalogue'};}
async function googleCatalogueUrls(q){const u='https://www.google.com/search?q='+encodeURIComponent('"'+q+'" site:orelhadelivro.com.br OR site:estantevirtual.com.br OR site:magazineluiza.com.br OR site:panini.com.br')+'&hl=pt-BR&num=10';const s=await html(u);const out=[];const re=/<a[^>]+href="(https?:\/\/[^"&]+)"/gi;let m;while((m=re.exec(s))&&out.length<12){const x=m[1];if(!out.includes(x)&&/orelhadelivro|estantevirtual|magazineluiza|panini\.com\.br/i.test(x))out.push(x);}return out;}
async function brSearch(q){const items=[];const seen=new Set();const add=x=>{if(!x||!x.title)return;const key=normISBN(x.isbn)||clean(x.title).toLowerCase();if(!seen.has(key)){seen.add(key);items.push(x);}};
 const isIsbn=/^(978|979)\d{10}$/.test(normISBN(q));
 const gbUrls=isIsbn?['https://www.googleapis.com/books/v1/volumes?q=isbn:'+encodeURIComponent(normISBN(q))+'&maxResults=20&country=BR','https://www.googleapis.com/books/v1/volumes?q=isbn:'+encodeURIComponent(normISBN(q))+'&maxResults=20']:['https://www.googleapis.com/books/v1/volumes?q='+encodeURIComponent(q)+'&maxResults=20&country=BR','https://www.googleapis.com/books/v1/volumes?q=intitle:'+encodeURIComponent(q)+'&maxResults=20&country=BR'];
 for(const u of gbUrls){const d=await json(u);for(const it of (d&&d.items)||[]){const v=it.volumeInfo||{};const ids=v.industryIdentifiers||[];const isbn=(ids.find(x=>/^97[89]/.test(String(x.identifier||'')))||ids[0]||{}).identifier||'';const l=v.imageLinks||{};add({title:v.title||'',authors:v.authors||[],publisher:v.publisher||'',publishedDate:v.publishedDate||'',language:v.language||'pt-BR',isbn:normISBN(isbn),cover:l.extraLarge||l.large||l.medium||l.thumbnail||l.smallThumbnail||'',url:'https://books.google.com/books?id='+encodeURIComponent(it.id),source:'Google Books BR'});}}
 const urls=await googleCatalogueUrls(q);for(const u of urls.slice(0,8)){const s=await html(u);if(s){const x=parseCataloguePage(s,u,isIsbn?normISBN(q):'');add(x);}}
 return {items:items.slice(0,20),source:'Brazil catalogues'};}
async function fetchImage(url){try{const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0','Accept':'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8'}});if(!r.ok)return null;const ct=r.headers.get('content-type')||'';if(!ct.toLowerCase().startsWith('image/'))return null;return new Response(r.body,{status:200,headers:{'Content-Type':ct,'Cache-Control':'public,max-age=86400'}});}catch(_){return null;}}
async function cover(isbn){const candidates=[];const add=x=>{if(x&&!candidates.includes(x))candidates.push(x);};const gb=await json('https://www.googleapis.com/books/v1/volumes?q=isbn:'+encodeURIComponent(isbn)+'&maxResults=10&country=BR');const items=(gb&&gb.items)||[];const exact=items.find(item=>((item.volumeInfo||{}).industryIdentifiers||[]).some(id=>normISBN(id.identifier)===isbn));const item=exact||items[0];const info=item&&item.volumeInfo;if(item&&item.id)add('https://books.google.com/books/content?id='+encodeURIComponent(item.id)+'&printsec=frontcover&img=1&zoom=2&source=gbs_api');const l=(info&&info.imageLinks)||{};add(l.extraLarge||l.large||l.medium||l.thumbnail||l.smallThumbnail);const ol=await json('https://openlibrary.org/isbn/'+encodeURIComponent(isbn)+'.json');if(ol&&ol.covers&&ol.covers[0])add('https://covers.openlibrary.org/b/id/'+ol.covers[0]+'-L.jpg');add('https://m.media-amazon.com/images/P/'+isbn+'.01.LZZZZZZZ.jpg');add('https://images-na.ssl-images-amazon.com/images/P/'+isbn+'.01.LZZZZZZZ.jpg');
 for(const u of await googleCatalogueUrls(isbn)){const s=await html(u);if(s)add(ogImage(s));}
 for(const c of candidates){const r=await fetchImage(c);if(r)return r;}
 return new Response('Cover not found',{status:404,headers:{'Cache-Control':'no-store'}});}
async function amazonSearch(q,market){const host=market==='br'?'https://www.amazon.com.br/s?k=':'https://www.amazon.es/s?k=';const s=await html(host+encodeURIComponent(q));const items=[];const seen=new Set();for(const block of s.split(/(?=<div[^>]+data-asin=)/i)){const m=block.match(/data-asin="([A-Z0-9]{10})"/i);if(!m||!m[1]||seen.has(m[1]))continue;seen.add(m[1]);const title=((block.match(/class="a-size-base-plus a-color-base a-text-normal"[^>]*>([\s\S]*?)<\/span>/i)||block.match(/class="a-size-medium a-color-base a-text-normal"[^>]*>([\s\S]*?)<\/span>/i)||[])[1]||'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').trim();if(title)items.push({asin:m[1],title});if(items.length>=10)break;}return {items};}
export default {async fetch(request,env){const url=new URL(request.url);try{if(url.pathname==='/api/br-search')return Response.json(await brSearch(clean(url.searchParams.get('q'))),{headers:{'Cache-Control':'public,max-age=300'}});if(url.pathname==='/api/cover')return cover(normISBN(url.searchParams.get('isbn')));if(url.pathname==='/api/amazon-search')return Response.json(await amazonSearch(clean(url.searchParams.get('q')),url.searchParams.get('market')||'es'),{headers:{'Cache-Control':'public,max-age=300'}});if(url.pathname.startsWith('/api/'))return Response.json({error:'Not found'},{status:404});return env.ASSETS.fetch(request);}catch(e){return Response.json({error:'Worker error',message:String(e&&e.message||e)},{status:500});}}};
